### ISSUE TITLE
Errors without default "derive" feature

### ISSUE THREAD

**Issue by dbr** [Joylei/anim-rs#1]
I'm playing with the library not using `iced` (seeing if it works nicely for an `imgui-rs` based UI), and came into this minor problem:

The example in the README doesn't build as
```
[dependencies]
anim = { version="0.1", default-features = false }
```
..will error because the derive feature is currently required (I get lots of errors of things not being defined due).

Workaround is easy enough - just need to define the `derive` feature then it builds nicely:

```
anim = { version="0.1", default-features = false, features = ["derive"] }
```

**Comment by Joylei** [comment]
features were not configured correctly.
